### ISSUE TITLE
Morning session code review

### ISSUE THREAD

**Issue by OscarFMdev** [Kelvin-Ben/math-magicians#6]
# Great job! 💯 

## Highlights:
- The code is looking clean. 🧹 
- The calculator logic works. 💪 

#### Optional suggestions
- I think you could improve the UI by using a grid. 👍 
- I think you could improve UX by showing the operations on the display. 🔢

##### Cheers and happy coding! 💻

**Comment by Kelvin-Ben** [comment]
@OscarFMdev  Thank you for theses suggestions. I will checkout them and implement in my project
